# Database Parameters
database:
  key_size: 16
  value_size: 200
  nr_entry: 536870912
  # nr_entry: 1000

# Workload Parameters
workload:
  nr_warmup_op: 10000000
  warmup_runtime_seconds: 240
  runtime_seconds: 60
  nr_op: 10000000
  nr_thread: 4
  next_op_interval_ns: 0  # use 50000 on mars
  operation_proportion:
    read: 1
    update: 0
    insert: 0
    scan: 0
    read_modify_write: 0
  request_distribution: "zipfian"
  # for zipfian distribution
  zipfian_constant: 0.99
  # for trace workload
  trace_file_list:
    - "./cur_trace"
  # for scan operation
  scan_length: 100

# LevelDB Parameters
leveldb:
  data_dir: "/mydata/leveldb_db_temp"
  options_file: "/mydata/My-YCSB/rocksdb/config/rocksdb_rubble_16gb_config.ini"
  cache_size: 100000000
  print_stats: true
