# Database Parameters
database:
  key_size: 16
  value_size: 100
  nr_entry: 2147483648

# Workload Parameters
workload:
  nr_warmup_op: 100000000
  warmup_runtime_seconds: 60
  runtime_seconds: 300
  nr_op: 100000000
  nr_thread: 64
  next_op_interval_ns: 0  # use 50000 on mars
  operation_proportion:
    read: 1
    update: 0
    insert: 0
    scan: 0
    read_modify_write: 0
  request_distribution: uniform
  # for zipfian distribution
  zipfian_constant: 0.6
  # for trace workload
  trace_file_list:
  - ./cur_trace
  # for scan operation
  scan_length: 100

# RocksDB Parameters
rocksdb:
  data_dir: /nvme/rocksdb_temp
  options_file: /mydata/My-YCSB/rocksdb/config_bigger/rocksdb_rubble_16gb_config.ini
  cache_size: 100000000
  print_stats: false
